GET /api/tickets/my HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5MjBmYTBiOS1mMGExLTRhNzItOGJkOC1lMDAyOTI2MzM3NjgiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjcxMzc1NDMsImV4cCI6MTc2NzIyMzk0M30.y9ODS3p0HNHJxT3WZ88-snzb3jLlFUZ5iEWk3_drxD0
Host: 127.0.0.1:8080

